/* Generated by cbindgen */

#ifndef CCZUNI_FFI_H
#define CCZUNI_FFI_H

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

typedef struct DefaultClient DefaultClient;

/**
 * 创建一个新的 cczuni 客户端实例。
 *
 * # Arguments
 * * `user` - C 字符串，用户的学号。
 * * `password` - C 字符串，用户的密码。
 *
 * # Returns
 * 返回一个指向客户端实例的不透明指针。如果创建失败，返回空指针。
 * **调用者必须在使用完毕后调用 `cczuni_client_free` 来释放内存。**
 */
struct DefaultClient *cczuni_client_new(const char *user, const char *password);

/**
 * 释放 cczuni 客户端实例占用的内存。
 *
 * # Arguments
 * * `client_ptr` - 通过 `cczuni_client_new` 创建的客户端指针。
 */
void cczuni_client_free(struct DefaultClient *client_ptr);

/**
 * 使用指定的客户端进行统一身份认证登录。
 *
 * # Arguments
 * * `client_ptr` - 客户端指针。
 *
 * # Returns
 * 返回一个 JSON 字符串，包含登录结果。
 * **返回的字符串必须使用 `cczuni_free_string` 进行释放。**
 */
char *cczuni_login(struct DefaultClient *client_ptr);

/**
 * 获取学生的成绩列表。
 *
 * # Arguments
 * * `client_ptr` - **已登录的**客户端指针。
 *
 * # Returns
 * 返回一个包含成绩信息的 JSON 字符串。
 * **返回的字符串必须使用 `cczuni_free_string` 进行释放。**
 */
char *cczuni_get_grades(struct DefaultClient *client_ptr);

/**
 * 获取学生的课表信息。
 *
 * # Arguments
 * * `client_ptr` - **已登录的**客户端指针。
 *
 * # Returns
 * 返回一个包含课表信息的 JSON 字符串。
 * **返回的字符串必须使用 `cczuni_free_string` 进行释放。**
 */
char *cczuni_get_schedule(struct DefaultClient *client_ptr);

/**
 * 获取各个服务的在线状态。
 *
 * # Returns
 * 返回一个包含服务状态的 JSON 字符串。
 * **返回的字符串必须使用 `cczuni_free_string` 进行释放。**
 */
char *cczuni_get_services_status(void);

/**
 * 释放由 cczuni 库函数返回的字符串所占用的内存。
 *
 * # Arguments
 * * `string_ptr` - 指向由其他 `cczuni_` 函数返回的 C 字符串的指针。
 */
void cczuni_free_string(char *string_ptr);

#endif  /* CCZUNI_FFI_H */
